CREATE TABLE pages (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  html TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE submissions (
  page_id TEXT PRIMARY KEY REFERENCES pages(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  submitted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
